In [9]:
#1
def occurrences(i, arr):
    count=0;
    for j in arr:
        if j==i:
            count=count+1
    print(count)
    
a = [1, 3, 5, 3, 7, 9, 3]
occurrences(3, a)

3


In [11]:
#2
def app(arr1, arr2):
    for x in a2:
        a1.append(x)
    print(a1)
a1=[1, 3, 5, 7, 9]
a2=[1, 3, 5, 7, 9]
app(a1, a2)

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9]


In [10]:
'''3'''
import numpy as n
Y = [12.23, 13.32, 100, 36.32]
print(Y)
X = n.array(Y)
print(X)

[12.23, 13.32, 100, 36.32]
[ 12.23  13.32 100.    36.32]


In [12]:
#4
import numpy as n 
arr = n.array([1,2,3])
s = arr.size 
print (s)
l = arr.itemsize
print (l)
t = arr.nbytes
print(t)


3
4
12


In [13]:
import numpy as n
A = n.array([[3, 7],[2, 4]])
R = 5 * A
print(R)

[[15 35]
 [10 20]]


In [15]:
import numpy as n 
U = n.array([3, -2])
V = n.array([5, 1])
D = n.dot(U,V)
print (D)

13


In [1]:
import numpy as n
A = n.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
B = n.array([[9, 8, 7],
            [6, 5, 4],
            [3, 2, 1]])
D = n.multiply(A, B)
print(D)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [14]:
import numpy as n
M = n.array([[4, 2, 1],
            [1, 3, 0],
            [2, 1, 5]])
X = n.array([2, -1, 3])
D = n.dot(M, X)
print(D)

[ 9 -1 18]


In [2]:
#6
import numpy as np
A = np.array([[3, 7], [2, 4]])
result_matrix = 5 * A
print(result_matrix)

[[15 35]
 [10 20]]


In [3]:
#7
A = [[3, 7], [2, 4]]
result_matrix = [[5 * element for element in row] for row in A]
for row in result_matrix:
    print(row)

[15, 35]
[10, 20]


In [4]:
#8
u = [3, -2]
v = [5, 1]
dot_product = u[0] * v[0] + u[1] * v[1]
print("Dot product of u and v:", dot_product)

Dot product of u and v: 13


In [5]:
#9
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
result = np.dot(A, B)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [ ]:
#10
import numpy as n
M = n.array([[[4, 2, 1],
[1, 3, 0],
[2, 1, 5]],
[[-1, 2, 3],
[0, -3, 1],
[2, 1, 0]]])
X = n.array([2, -1, 3])
D = n.dot(M, X)
print(D)


In [19]:
import numpy as n
sum=0
prime = n.array([2 ,3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71])
for x in prime:
	sum = sum + x
print (sum)

639


In [20]:
import numpy as np
temperatures = np.array([25.5, 26.2, 24.8, 23.5, 27.0, 25.9, 28.3])
print(temperatures)
mean = np.mean(temperatures)
print(mean)
indices = np.where(temperatures > mean)
print(indices)

[25.5 26.2 24.8 23.5 27.  25.9 28.3]
25.88571428571429
(array([1, 4, 5, 6], dtype=int64),)


In [21]:
import numpy as n
array = n.arange(10,51)
print (array)
extract = array[5:16]
print ("\n",extract)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

 [15 16 17 18 19 20 21 22 23 24 25]


In [22]:
import numpy as np
matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]])
print(matrix,"\n")
submatrix = matrix[1:3,1:3]
print(submatrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[[ 6  7]
 [10 11]]


In [23]:
import numpy as np
random = np.random.rand(5, 5)
print (random)
diagonall = np.diagonal(random)
print (diagonall)

[[0.17266998 0.7705395  0.66488711 0.19024762 0.91845736]
 [0.5904469  0.61128616 0.57100172 0.87156718 0.39575481]
 [0.17480298 0.08907245 0.37548601 0.58549068 0.11535605]
 [0.17488206 0.25157326 0.65179316 0.92292375 0.6606202 ]
 [0.69692172 0.86700684 0.83382112 0.04327357 0.64982709]]
[0.17266998 0.61128616 0.37548601 0.92292375 0.64982709]


In [24]:
import numpy as np
tensor = np.random.rand(3, 4, 5)
print(tensor)
subarray = tensor[1:3, 0, :]
print("\n",subarray)

[[[0.54183103 0.49980458 0.13531587 0.70843636 0.98008952]
  [0.486095   0.09911059 0.57435803 0.45840845 0.26480203]
  [0.01343832 0.81039386 0.53533926 0.92355338 0.27883859]
  [0.75355177 0.58806347 0.61510585 0.96725128 0.23712155]]

 [[0.43878856 0.18974885 0.159269   0.96620052 0.65929655]
  [0.55565293 0.60692072 0.62489955 0.00753085 0.23755702]
  [0.13513892 0.87577782 0.40159771 0.52687814 0.14322783]
  [0.88002958 0.23444163 0.89036708 0.89365065 0.4469998 ]]

 [[0.51244828 0.11817227 0.06393199 0.69408776 0.28441276]
  [0.10431043 0.93079157 0.35342467 0.91371562 0.42811466]
  [0.99264722 0.11433728 0.98269558 0.39808835 0.7671366 ]
  [0.03573412 0.15966085 0.80482068 0.48848447 0.80772693]]]

 [[0.43878856 0.18974885 0.159269   0.96620052 0.65929655]
 [0.51244828 0.11817227 0.06393199 0.69408776 0.28441276]]


In [25]:
import numpy as np
data = np.array([10, 25, 15, 30, 20, 35, 5])
print(data)
mean = np.mean(data)
print(mean)
new_array = data[data > mean]
print(new_array)

[10 25 15 30 20 35  5]
20.0
[25 30 35]


In [26]:
import numpy as np
array = np.random.randint(1, 101, size=(5, 3))
print(array)
rows = array[np.sum(array[:, 1]) > 150]
print(rows)

[[36 40 36]
 [52 15 84]
 [26 41 42]
 [61 84 59]
 [73 73 43]]
[[[36 40 36]
  [52 15 84]
  [26 41 42]
  [61 84 59]
  [73 73 43]]]
